"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { BadgeCheck, Bot, LockKeyhole, MessageCircle, Send, Sparkles, Trophy } from "lucide-react";
import { getStoredAuthUser } from "@/lib/auth-client";
interface LobbyMessage { id: string; author: string; text: string; createdAt: string; }
export function MatchLobby({ matchId }: { matchId: string }) {
  const key = `proclubs-america-lobby-${matchId}`; const [messages, setMessages] = useState<LobbyMessage[]>([]); const [text, setText] = useState(""); const [user, setUser] = useState<ReturnType<typeof getStoredAuthUser>>(null);
  useEffect(() => { const timer = setTimeout(() => { setUser(getStoredAuthUser()); try { setMessages(JSON.parse(localStorage.getItem(key) ?? "[]")); } catch {} }, 0); return () => clearTimeout(timer); }, [key]);
  function submit(event: FormEvent) { event.preventDefault(); if (!user || !text.trim()) return; const next = [...messages, { id: crypto.randomUUID(), author: user.name, text: text.trim(), createdAt: new Date().toISOString() }]; setMessages(next); localStorage.setItem(key, JSON.stringify(next)); setText(""); }
  return <section className="match-community-tools"><article className="elo-preview"><header><Trophy /><div><small>ELO DO AMISTOSO</small><h2>Impacto projetado</h2></div><span>EM TESTE</span></header><div><strong>+18</strong><span>Vitória contra rival superior</span><b>−12</b><span>Derrota esperada</span></div><footer><BadgeCheck /> Confiabilidade e pontualidade influenciarão o matchmaking.</footer></article><article className="match-lobby"><header><MessageCircle /><div><small>LOBBY DO JOGO</small><h2>Combinar sala</h2></div><span>{messages.length} mensagens</span></header><div className="lobby-messages">{messages.length ? messages.map((message) => <p key={message.id}><strong>{message.author}</strong>{message.text}<small>{new Date(message.createdAt).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</small></p>) : <div><MessageCircle /> Nenhuma mensagem. Combine servidor e nome da sala.</div>}</div>{user ? <form onSubmit={submit}><input value={text} onChange={(event) => setText(event.target.value)} placeholder="Escreva para o adversário" aria-label="Mensagem do lobby" /><button aria-label="Enviar mensagem"><Send /></button></form> : <Link href="/entrar"><LockKeyhole /> Entre para conversar no lobby</Link>}<footer><Bot /> Bot do Discord preparado — webhook ainda não configurado.</footer></article><Link className="vip-match-banner" href="/planos"><Sparkles /><span>DESTAQUE PRO/VIP<strong>Fixar desafio, histórico completo e estatísticas avançadas</strong></span></Link></section>;
}
