"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, CalendarDays, Clock3, ExternalLink, LockKeyhole, MapPin, ShieldCheck, Swords, Trophy, Users } from "lucide-react";
import type { MatchRecord } from "@/types/domain";
import type { CommunityMatchClub } from "@/lib/friendlies-data";
import type { FriendlyRequest } from "@/lib/friendlies";
import { getOfficialMatch, watchFriendly } from "@/lib/community-service";
import { MobileNav } from "./mobile-nav";
import { PlatformHeader } from "./platform-header";
import { MatchLobby } from "./match-lobby";
import { EaSourceSubmission } from "./ea-source-submission";
export function MatchDetail({ id, official, clubs }: { id: string; official?: MatchRecord; clubs: CommunityMatchClub[] }) {
  const [request, setRequest] = useState<FriendlyRequest | null>(null); const [liveOfficial, setLiveOfficial] = useState<MatchRecord | null>(null); const [communityLoaded, setCommunityLoaded] = useState(Boolean(official)); const [officialLoaded, setOfficialLoaded] = useState(Boolean(official));
  useEffect(() => { if (official) return; getOfficialMatch(id).then(setLiveOfficial).catch(() => undefined).finally(() => setOfficialLoaded(true)); return watchFriendly(id, (item) => { setRequest(item); setCommunityLoaded(true); }, () => setCommunityLoaded(true)); }, [id, official]);
  const resolvedOfficial = official ?? liveOfficial;
  if (!resolvedOfficial && officialLoaded && communityLoaded && !request) return <main className="app-shell"><PlatformHeader /><div className="match-not-found"><Swords /><h1>Partida não encontrada</h1><p>O convite não existe ou não está mais disponível.</p><Link href="/partidas">Voltar para partidas</Link></div><MobileNav /></main>;
  const hostId = resolvedOfficial?.homeClubId ?? request?.hostClubId; const awayId = resolvedOfficial?.awayClubId ?? request?.opponentClubId ?? request?.invitedClubId; const host = clubs.find((club) => club.id === hostId); const away = clubs.find((club) => club.id === awayId); const homeName = resolvedOfficial?.homeClubName ?? request?.hostClubName ?? "Time da casa"; const awayName = resolvedOfficial?.awayClubName ?? request?.opponentClubName ?? request?.invitedClubName ?? "Adversário em aberto";
  return <main className="app-shell match-detail-page"><PlatformHeader /><section className="match-detail-hero"><Link href="/partidas"><ArrowLeft /> Partidas</Link><small>{resolvedOfficial ? "RESULTADO OFICIAL" : request?.status === "scheduled" ? "JOGO AGENDADO" : "DESAFIO DA COMUNIDADE"}</small><div className="match-detail-score"><section><span>{homeName.slice(0,2).toUpperCase()}</span><h1>{homeName}</h1><small>{host?.roster.length ?? 0} jogadores publicados</small></section><b>{resolvedOfficial ? <>{resolvedOfficial.homeScore}<i>×</i>{resolvedOfficial.awayScore}</> : <><i>×</i></>}</b><section><span>{awayName.slice(0,2).toUpperCase()}</span><h1>{awayName}</h1><small>{away?.roster.length ?? 0} jogadores publicados</small></section></div><div className="match-detail-meta">{resolvedOfficial ? <><span><CalendarDays />{new Date(resolvedOfficial.playedAt).toLocaleString("pt-BR")}</span><span><Trophy />{resolvedOfficial.competition}</span><a href={resolvedOfficial.sourceUrl} target="_blank" rel="noreferrer">Fonte EA <ExternalLink /></a></> : <><span><CalendarDays />{request && new Date(`${request.date}T12:00:00`).toLocaleDateString("pt-BR")}</span><span><Clock3 />{request?.time}</span><span><MapPin />{request?.region}</span></>}</div></section><section className="match-detail-content"><article className="match-status-panel"><ShieldCheck /><div><small>VALIDAÇÃO DO PLACAR</small><h2>{resolvedOfficial ? "Confirmado pela fonte pública" : request?.status === "waiting_ea" ? "Aguardando publicação oficial da EA" : "Placar manual bloqueado"}</h2><p>{resolvedOfficial ? "Este resultado foi incorporado do histórico público do clube." : "Quando o confronto aparecer na aba Friendly da EA, o reconciliador poderá preencher placar e estatísticas automaticamente."}</p></div><LockKeyhole /></article>{request?.status === "waiting_ea" ? <EaSourceSubmission match={request} /> : null}<div className="match-squads">{[{ club: host, name: homeName }, { club: away, name: awayName }].map((team, index) => <article key={team.club?.id ?? index}><header><Users /><div><small>{index ? "VISITANTE" : "CASA"}</small><h2>{team.name}</h2></div><span>SR {team.club?.skillRating ?? "—"}</span></header><div>{team.club?.roster.length ? team.club.roster.slice(0,11).map((player, playerIndex) => <span key={`${player.name}-${playerIndex}`}><b>{String(playerIndex+1).padStart(2,"0")}</b><strong>{player.name}</strong><small>{player.position}</small></span>) : <p>Escalação ainda não publicada.</p>}</div></article>)}</div>{resolvedOfficial?.players.length ? <article className="match-player-stats"><header><Trophy /><h2>Estatísticas da partida</h2></header>{resolvedOfficial.players.map((player) => <div key={player.playerId}><strong>{player.playerName}</strong><span>{player.goals} G</span><span>{player.assists} A</span><span>{player.tacklesMade ?? 0} desarmes</span><b>{player.rating ?? "—"}</b></div>)}</article> : null}{request ? <MatchLobby match={request} /> : null}</section><MobileNav /></main>;
}
