"use client";

import { LockKeyhole, Gamepad2, UserRoundSearch } from "lucide-react";
import { playerDevices, positionGroups } from "@/lib/player-identity";
import type { LocaleId } from "@/lib/i18n";
import styles from "./onboarding.module.css";

export interface IdentityDraft { nickname: string; displayName: string; phone: string; gamingPlatform: string; preferredPosition: string; lookingForClub: boolean; }
export const emptyIdentity: IdentityDraft = { nickname: "", displayName: "", phone: "", gamingPlatform: "", preferredPosition: "", lookingForClub: false };
export const identityCopy = {
  "pt-br": { profile: "Seu perfil", title: "Seu lugar no elenco.", intro: "Mostre como quer ser conhecido. O resto a gente simplifica.", nick: "Seu nick", nickHint: "Único na comunidade. 3 a 24 letras, números ou hífen.", name: "Seu nome", nameHint: "Como você aparece no card e no elenco.", phone: "Telefone (opcional)", phoneHint: "Com + e código do país. Só você e a administração têm acesso; nunca aparece no perfil ou mercado.", device: "Onde você joga (opcional)", noDevice: "Prefiro informar depois", current: "Geração atual", previous: "Geração anterior", switch2: "Switch 2", switch: "Switch", generationHint: "Informe seu console exato para encontrar jogadores da mesma geração.", switchHint: "O catálogo de times do Switch 2 ainda não está integrado. Você pode continuar sem time.", position: "Sua posição (opcional)", noPosition: "Sem posição", goal: "Gol", defense: "Defesa", midfield: "Meio", attack: "Ataque", available: "Estou procurando clube", availableHint: "Seu perfil entra na vitrine do mercado. Você pode mudar depois em Minha conta.", signedIn: "Entrando como", signOut: "Não é você? Sair", publicAddress: "Seu perfil público", invalidNick: "Use de 3 a 24 letras, números ou hífen; comece e termine com letra ou número.", invalidName: "Informe seu nome com 2 a 60 caracteres.", invalidPhone: "Use +, código do país e número, ou deixe em branco.", nickTaken: "Esse nick já tem dono. Escolha outro para seu perfil.", catalog: "Catálogo de times", locked: "Seu time atual está mantido. Alterações de vínculo são feitas pela conta." },
  es: { profile: "Tu perfil", title: "Tu lugar en el equipo.", intro: "Elige cómo quieres que te conozcan. Nosotros simplificamos el resto.", nick: "Tu nick", nickHint: "Único en la comunidad. De 3 a 24 letras, números o guion.", name: "Tu nombre", nameHint: "Como apareces en tu tarjeta y en el equipo.", phone: "Teléfono (opcional)", phoneHint: "Con + y código de país. Solo tú y la administración tienen acceso; nunca aparece en tu perfil o mercado.", device: "Dónde juegas (opcional)", noDevice: "Lo indicaré después", current: "Generación actual", previous: "Generación anterior", switch2: "Switch 2", switch: "Switch", generationHint: "Indica tu consola exacta para encontrar jugadores de la misma generación.", switchHint: "El catálogo de equipos de Switch 2 aún no está integrado. Puedes continuar sin equipo.", position: "Tu posición (opcional)", noPosition: "Sin posición", goal: "Portería", defense: "Defensa", midfield: "Medio", attack: "Ataque", available: "Estoy buscando equipo", availableHint: "Tu perfil aparece en el mercado. Puedes cambiarlo después en Mi cuenta.", signedIn: "Entrando como", signOut: "¿No eres tú? Salir", publicAddress: "Tu perfil público", invalidNick: "Usa de 3 a 24 letras, números o guion; empieza y termina con letra o número.", invalidName: "Indica un nombre de 2 a 60 caracteres.", invalidPhone: "Usa +, código de país y número, o deja el campo vacío.", nickTaken: "Ese nick ya está en uso. Elige otro para tu perfil.", catalog: "Catálogo de equipos", locked: "Se conserva tu equipo actual. Los cambios de vínculo se realizan desde tu cuenta." },
  en: { profile: "Your profile", title: "Your place in the squad.", intro: "Choose how you want to be known. We'll keep the rest simple.", nick: "Your nickname", nickHint: "Unique in the community. 3–24 letters, numbers or hyphens.", name: "Your name", nameHint: "How you appear on your card and in the squad.", phone: "Phone (optional)", phoneHint: "Include + and country code. Only you and the administration can access it; never shown on your profile or in the market.", device: "Where you play (optional)", noDevice: "I'll choose later", current: "Current generation", previous: "Previous generation", switch2: "Switch 2", switch: "Switch", generationHint: "Choose your exact console to find players in the same generation.", switchHint: "The Switch 2 team catalog is not integrated yet. You can continue without a team.", position: "Your position (optional)", noPosition: "No position", goal: "Goal", defense: "Defense", midfield: "Midfield", attack: "Attack", available: "I'm looking for a club", availableHint: "Your profile appears in the market. Change this later in My account.", signedIn: "Signed in as", signOut: "Not you? Sign out", publicAddress: "Your public profile", invalidNick: "Use 3–24 letters, numbers or hyphens; start and end with a letter or number.", invalidName: "Enter a name with 2–60 characters.", invalidPhone: "Use +, country code and number, or leave it empty.", nickTaken: "That nickname is already in use. Choose another one.", catalog: "Team catalog", locked: "Your current team is retained. Membership changes are handled from your account." },
};
type FieldsProps = { value: IdentityDraft; onChange: (patch: Partial<IdentityDraft>) => void; locale: LocaleId; disabled: boolean };

export function ProfileIdentityFields({ value, onChange, locale, disabled }: FieldsProps) {
  const t = identityCopy[locale];
  return <fieldset className={styles.identityFields} disabled={disabled}>
    <label className={styles.field}>{t.nick}<span className={styles.search}><span aria-hidden="true">@</span><input name="nickname" autoComplete="username" autoCapitalize="none" spellCheck={false} minLength={3} maxLength={24} required pattern="[a-zA-Z0-9][a-zA-Z0-9\-]{1,22}[a-zA-Z0-9]" value={value.nickname} onChange={(event) => onChange({ nickname: event.target.value.toLowerCase() })} aria-describedby="nick-hint" /></span><small id="nick-hint" className={styles.hint}>{t.nickHint}</small></label>
    <div className={styles.address}><small>{t.publicAddress}</small><span>proclubsamerica.com/perfil?id=<b>{value.nickname || "seu-nick"}</b></span></div>
    <label className={styles.field}>{t.name}<input name="displayName" autoComplete="nickname" minLength={2} maxLength={60} required value={value.displayName} onChange={(event) => onChange({ displayName: event.target.value })} /><small className={styles.hint}>{t.nameHint}</small></label>
    <label className={styles.field}>{t.phone}<input name="phone" type="tel" autoComplete="tel" placeholder="+55 11 99999-9999" maxLength={40} value={value.phone} onChange={(event) => onChange({ phone: event.target.value })} aria-describedby="phone-hint" /><small id="phone-hint" className={styles.hint}><LockKeyhole size={13} aria-hidden="true" /> {t.phoneHint}</small></label>
  </fieldset>;
}

export function PlayingIdentityFields({ value, onChange, locale, disabled }: FieldsProps) {
  const t = identityCopy[locale];
  return <fieldset className={styles.identityFields} disabled={disabled}>
    <fieldset className={styles.choices}><legend><Gamepad2 size={20} />{t.device}</legend>
      <label className={styles.pill}><input type="radio" name="gamingPlatform" checked={!value.gamingPlatform} onChange={() => onChange({ gamingPlatform: "" })} />{t.noDevice}</label>
      {(["current", "previous", "switch2", "switch"] as const).map((generation) => <div className={styles.optionGroup} key={generation}><small>{t[generation]}</small><div className={styles.pills}>{playerDevices.filter((device) => device.generation === generation).map((device) => <label className={styles.pill} key={device.id}><input type="radio" name="gamingPlatform" checked={value.gamingPlatform === device.id} onChange={() => onChange({ gamingPlatform: device.id })} />{device.label}</label>)}</div></div>)}
      <small className={styles.hint}>{value.gamingPlatform === "switch-2" ? t.switchHint : t.generationHint}</small>
    </fieldset>
    <fieldset className={styles.choices}><legend>{t.position}</legend><label className={styles.pill}><input type="radio" name="preferredPosition" checked={!value.preferredPosition} onChange={() => onChange({ preferredPosition: "" })} />{t.noPosition}</label>{positionGroups.map((group) => <div className={styles.optionGroup} key={group.id}><small>{t[group.id]}</small><div className={styles.pills}>{group.positions.map((position) => <label className={styles.pill} key={position}><input type="radio" name="preferredPosition" checked={value.preferredPosition === position} onChange={() => onChange({ preferredPosition: position })} />{position}</label>)}</div></div>)}</fieldset>
    <label className={styles.availability}><UserRoundSearch size={22} aria-hidden="true" /><span><strong>{t.available}</strong><small>{t.availableHint}</small></span><input type="checkbox" checked={value.lookingForClub} onChange={(event) => onChange({ lookingForClub: event.target.checked })} /></label>
  </fieldset>;
}
