import Image from "next/image";
import Link from "next/link";
import { ExternalLink, Goal, Medal, ShieldCheck, Swords, Trophy, Users } from "lucide-react";
import type { PublicClub, PublicPlayer } from "@/lib/public-data";
import { MobileNav } from "./mobile-nav";
import { PlatformHeader } from "./platform-header";

export function PublicClubProfile({ club, players }: { club: PublicClub; players: PublicPlayer[] }) {
  return <main className="app-shell public-club-page"><PlatformHeader />
    <section className="public-club-hero"><Image src={club.crestUrl} alt={`Escudo ${club.name}`} width={130} height={130} unoptimized /><div><small>RANKING EA · #{club.rank}</small><h1>{club.name}</h1><p>{club.platform} · Divisão atual {club.currentDivision || "—"}{club.stadium ? ` · ${club.stadium}` : ""}</p></div><div className="club-hero-actions"><Link href={`/partidas/amistosos?desafiar=${club.id}&nome=${encodeURIComponent(club.name)}#buscar-amistoso`}><Swords /> Desafiar clube</Link><a href={club.sourceUrl} target="_blank" rel="noreferrer">Fonte pública <ExternalLink /></a></div></section>
    <div className="public-club-content"><section className="player-kpis"><article><small>SKILL RATING</small><strong>{club.skillRating}</strong></article><article><small>JOGOS</small><strong>{club.matches}</strong></article><article><small>VITÓRIAS</small><strong>{club.wins}</strong></article><article><small>WIN RATE</small><strong>{club.winRate}%</strong></article><article><small>GOLS</small><strong>{club.goals}</strong></article><article><small>CLEAN SHEETS</small><strong>{club.cleanSheets}</strong></article></section>
      <section className="public-club-panels"><article><header><Trophy /><div><small>DESEMPENHO</small><h2>Campanha do clube</h2></div></header><div className="club-record-grid"><span><b>{club.wins}</b>Vitórias</span><span><b>{club.draws}</b>Empates</span><span><b>{club.losses}</b>Derrotas</span><span><b>{club.goalsAgainst}</b>Gols sofridos</span><span><b>{club.goalsPerGame}</b>Gols/jogo</span><span><b>{club.goals - club.goalsAgainst > 0 ? "+" : ""}{club.goals - club.goalsAgainst}</b>Saldo</span></div></article><article><header><Medal /><div><small>POSIÇÃO</small><h2>Ranking público</h2></div></header><strong className="world-rank">#{club.rank}</strong><p>Entre os 100 clubes coletados em common-gen5.</p></article></section>
      <section className="directory-section"><header><div><small>ELENCO PUBLICADO</small><h2>{players.length} jogadores coletados</h2></div><Link href="/rankings/jogadores/artilharia">Ver rankings</Link></header>{players.length ? <div className="directory-player-grid">{players.map((player) => <Link href={`/jogador/${player.id}`} key={player.id}><span>{player.averageRating ?? "—"}</span><div><strong>{player.name}</strong><small>{player.position} · {player.matches} jogos</small></div><b>{player.goals} G</b></Link>)}</div> : <div className="directory-empty"><Users /> O elenco detalhado ainda não foi incluído nesta extração.</div>}</section>
      <aside className="public-source-note"><ShieldCheck /><span>Dados esportivos extraídos da página pública da EA em 09/08/2026. Valores ausentes não são estimados.</span><Goal /></aside>
    </div><MobileNav /></main>;
}
