"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { BriefcaseBusiness, Clock3, Search, Shield, UserRoundSearch, Users } from "lucide-react";
import { MobileNav } from "./mobile-nav";
import { PlatformHeader } from "./platform-header";
import { observeAuth, type AuthUserSnapshot } from "@/lib/auth-client";
import { publishTransferPost, watchTransferPosts, type TransferPostRecord } from "@/lib/community-service";

type TransferPost = TransferPostRecord;

export function TransferMarket({ initialType = "club_vacancy" }: { initialType?: TransferPost["type"] }) {
  const [posts, setPosts] = useState<TransferPost[]>([]);
  const [type, setType] = useState<TransferPost["type"]>(initialType);
  const [filter, setFilter] = useState<"all" | TransferPost["type"]>("all");
  const [user, setUser] = useState<AuthUserSnapshot | null>(null);
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState("");
  const visible = useMemo(() => posts.filter((post) => filter === "all" || post.type === filter).sort((a, b) => ({ vip: 2, pro: 1, free: 0 }[b.plan] - { vip: 2, pro: 1, free: 0 }[a.plan]) || b.createdAt.localeCompare(a.createdAt)), [filter, posts]);
  useEffect(() => { const stopAuth = observeAuth(setUser); const stopPosts = watchTransferPosts(setPosts, () => setNotice("Não foi possível carregar o mercado em tempo real.")); return () => { stopAuth(); stopPosts(); }; }, []);

  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!user) { setNotice("Entre na sua conta para publicar no mercado."); return; } const formElement = event.currentTarget; const form = new FormData(formElement); const minimumOvr = Number(form.get("minimumOvr") || 0) || undefined; setBusy(true); setNotice(""); try { await publishTransferPost({ type, title: String(form.get("title")), owner: String(form.get("owner")), position: String(form.get("position")), minimumOvr, platform: String(form.get("platform")), availability: String(form.get("availability")), contact: String(form.get("contact")) }); formElement.reset(); setNotice("Anúncio publicado para toda a comunidade."); } catch { setNotice("Não foi possível publicar o anúncio."); } finally { setBusy(false); } }

  return <main className="app-shell transfer-page"><PlatformHeader />
    <section className="transfer-hero"><div><small>MERCADO DA COMUNIDADE</small><h1>Encontre seu próximo time</h1><p>Clubes divulgam vagas abertas. Jogadores publicam disponibilidade e posição para receber propostas.</p></div><BriefcaseBusiness /></section>
    <div className="transfer-layout"><form className="transfer-form" id="nova-vaga" onSubmit={submit}><header><div><small>PUBLICAR ANÚNCIO</small><h2>{type === "club_vacancy" ? "Meu clube procura jogador" : "Sou jogador e procuro clube"}</h2></div></header>{!user && <p className="registration-error">Para publicar, <Link href="/entrar">entre na sua conta</Link>.</p>}<div className="transfer-type"><button className={type === "club_vacancy" ? "active" : ""} type="button" onClick={() => setType("club_vacancy")}><Shield /> Vaga em clube</button><button className={type === "player_search" ? "active" : ""} type="button" onClick={() => setType("player_search")}><UserRoundSearch /> Jogador livre</button></div><label>{type === "club_vacancy" ? "Título da vaga" : "Nome público do jogador"}<input required name="title" placeholder={type === "club_vacancy" ? "Ex.: Procuramos volante" : "Ex.: Gabriel_CDM"} /></label><label>{type === "club_vacancy" ? "Nome do clube" : "Clube atual ou Livre"}<input required name="owner" /></label><div className="registration-pair"><label>Posição<select required name="position"><option>Qualquer</option><option>Goleiro</option><option>Defensor</option><option>Meio-campo</option><option>Atacante</option></select></label><label>OVR mínimo<input name="minimumOvr" type="number" min="1" max="99" placeholder="Ex.: 85" /></label></div><label>Plataforma<select required name="platform"><option value="common-gen5">PS5 / Xbox Series / PC</option><option value="common-gen4">PS4 / Xbox One</option><option value="nx">Nintendo Switch</option></select></label><label>Disponibilidade<input required name="availability" placeholder="Ex.: Seg–Qui, 21h às 00h" /></label><label>Contato público<input required name="contact" placeholder="Discord, PSN ou gamertag" /></label><button type="submit" disabled={!user || busy}>{busy ? "Publicando…" : "Publicar no mercado"} <BriefcaseBusiness /></button>{notice && <small className="local-note" role="status">{notice}</small>}</form>
      <section className="transfer-list"><div className="market-title"><div><small>OPORTUNIDADES</small><h2>Mercado de transferências</h2></div><span>{visible.length} anúncios</span></div><div className="match-filters"><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>Todos</button><button className={filter === "club_vacancy" ? "active" : ""} onClick={() => setFilter("club_vacancy")}>Vagas em clubes</button><button className={filter === "player_search" ? "active" : ""} onClick={() => setFilter("player_search")}>Jogadores livres</button></div>{visible.length ? visible.map((post) => <article className="transfer-card" key={post.id}><span>{post.type === "club_vacancy" ? <Shield /> : <UserRoundSearch />}</span><div><small>{post.type === "club_vacancy" ? "CLUBE RECRUTANDO" : "JOGADOR DISPONÍVEL"}{post.plan !== "free" ? ` · ${post.plan.toUpperCase()}` : ""}</small><h3>{post.title}</h3><p>{post.owner}{post.minimumOvr ? ` · OVR ${post.minimumOvr}+` : ""}</p><dl><span><Users /> {post.position}</span><span><Clock3 /> {post.availability}</span></dl></div><aside><small>{post.platform}</small><strong>{post.contact}</strong><time>{new Date(post.createdAt).toLocaleDateString("pt-BR")}</time></aside></article>) : <div className="transfer-empty"><Search /><strong>Nenhum anúncio neste filtro</strong><span>Publique a primeira oportunidade real da comunidade.</span></div>}</section>
    </div><MobileNav /></main>;
}
