"use client";

import { FormEvent, useMemo, useState } from "react";
import { BriefcaseBusiness, Clock3, Search, Shield, UserRoundSearch, Users } from "lucide-react";
import { MobileNav } from "./mobile-nav";
import { PlatformHeader } from "./platform-header";

interface TransferPost { id: string; type: "club_vacancy" | "player_search"; title: string; owner: string; position: string; platform: string; availability: string; contact: string; createdAt: string; }
const storageKey = "clubs-brasil-transfer-market";

export function TransferMarket({ initialType = "club_vacancy" }: { initialType?: TransferPost["type"] }) {
  const [posts, setPosts] = useState<TransferPost[]>(() => { if (typeof window === "undefined") return []; try { return JSON.parse(localStorage.getItem(storageKey) ?? "[]"); } catch { return []; } });
  const [type, setType] = useState<TransferPost["type"]>(initialType);
  const [filter, setFilter] = useState<"all" | TransferPost["type"]>("all");
  const visible = useMemo(() => posts.filter((post) => filter === "all" || post.type === filter), [filter, posts]);

  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const post: TransferPost = { id: crypto.randomUUID(), type, title: String(form.get("title")), owner: String(form.get("owner")), position: String(form.get("position")), platform: String(form.get("platform")), availability: String(form.get("availability")), contact: String(form.get("contact")), createdAt: new Date().toISOString() }; const next = [post, ...posts]; setPosts(next); localStorage.setItem(storageKey, JSON.stringify(next)); event.currentTarget.reset(); }

  return <main className="app-shell transfer-page"><PlatformHeader />
    <section className="transfer-hero"><div><small>MERCADO DA COMUNIDADE</small><h1>Encontre seu próximo time</h1><p>Clubes divulgam vagas abertas. Jogadores publicam disponibilidade e posição para receber propostas.</p></div><BriefcaseBusiness /></section>
    <div className="transfer-layout"><form className="transfer-form" id="nova-vaga" onSubmit={submit}><header><div><small>PUBLICAR ANÚNCIO</small><h2>{type === "club_vacancy" ? "Meu clube procura jogador" : "Sou jogador e procuro clube"}</h2></div></header><div className="transfer-type"><button className={type === "club_vacancy" ? "active" : ""} type="button" onClick={() => setType("club_vacancy")}><Shield /> Vaga em clube</button><button className={type === "player_search" ? "active" : ""} type="button" onClick={() => setType("player_search")}><UserRoundSearch /> Jogador livre</button></div><label>{type === "club_vacancy" ? "Título da vaga" : "Nome público do jogador"}<input required name="title" placeholder={type === "club_vacancy" ? "Ex.: Procuramos volante" : "Ex.: Gabriel_CDM"} /></label><label>{type === "club_vacancy" ? "Nome do clube" : "Clube atual ou Livre"}<input required name="owner" /></label><div className="registration-pair"><label>Posição<select required name="position"><option>Qualquer</option><option>Goleiro</option><option>Defensor</option><option>Meio-campo</option><option>Atacante</option></select></label><label>Plataforma<select required name="platform"><option value="common-gen5">PS5 / Xbox Series / PC</option><option value="common-gen4">PS4 / Xbox One</option><option value="nx">Nintendo Switch</option></select></label></div><label>Disponibilidade<input required name="availability" placeholder="Ex.: Seg–Qui, 21h às 00h" /></label><label>Contato público<input required name="contact" placeholder="Discord, PSN ou gamertag" /></label><button type="submit">Publicar no mercado <BriefcaseBusiness /></button><small className="local-note">Protótipo: anúncios ficam salvos neste navegador até a integração do backend comunitário.</small></form>
      <section className="transfer-list"><div className="market-title"><div><small>OPORTUNIDADES</small><h2>Mercado de transferências</h2></div><span>{visible.length} anúncios</span></div><div className="match-filters"><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>Todos</button><button className={filter === "club_vacancy" ? "active" : ""} onClick={() => setFilter("club_vacancy")}>Vagas em clubes</button><button className={filter === "player_search" ? "active" : ""} onClick={() => setFilter("player_search")}>Jogadores livres</button></div>{visible.length ? visible.map((post) => <article className="transfer-card" key={post.id}><span>{post.type === "club_vacancy" ? <Shield /> : <UserRoundSearch />}</span><div><small>{post.type === "club_vacancy" ? "CLUBE RECRUTANDO" : "JOGADOR DISPONÍVEL"}</small><h3>{post.title}</h3><p>{post.owner}</p><dl><span><Users /> {post.position}</span><span><Clock3 /> {post.availability}</span></dl></div><aside><small>{post.platform}</small><strong>{post.contact}</strong><time>{new Date(post.createdAt).toLocaleDateString("pt-BR")}</time></aside></article>) : <div className="transfer-empty"><Search /><strong>Nenhum anúncio neste filtro</strong><span>Publique a primeira oportunidade real da comunidade.</span></div>}</section>
    </div><MobileNav /></main>;
}
